;;; meadow-font.el
;;; Copyright (C) 2010 YASUDA Jiro

;;; Author: YASUDA Jiro
;;; Time:   '10/08/25


(defun yas-create-fontset (ascii-font jis-font size mul)
  (w32-add-font
   (concat "fontset-" ascii-font (int-to-string size))
   '((strict-spec
      ((:char-spec ascii :height any)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0 nil nil nil 128 1 3 1))
      ((:char-spec ascii :height any :weight bold)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0 nil nil nil 128 1 3 1))
      ((:char-spec ascii :height any :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0   t nil nil 128 1 3 1))
      ((:char-spec ascii :height any :weight bold :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0   t nil nil 128 1 3 1))
      ((:char-spec japanese-jisx0208 :height any)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0 nil nil nil 128 1 3 49))
      ((:char-spec japanese-jisx0208 :height any :weight bold)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0 nil nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec japanese-jisx0208 :height any :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0   t nil nil 128 1 3 49))
      ((:char-spec japanese-jisx0208 :height any :weight bold :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0   t nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec katakana-jisx0201 :height any)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0 nil nil nil 128 1 3 49))
      ((:char-spec katakana-jisx0201 :height any :weight bold)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0 nil nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec katakana-jisx0201 :height any :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0   t nil nil 128 1 3 49))
      ((:char-spec katakana-jisx0201 :height any :weight bold :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0   t nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec japanese-jisx0213-1 :height any)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0 nil nil nil 128 1 3 49))
      ((:char-spec japanese-jisx0213-1 :height any :weight bold)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0 nil nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec japanese-jisx0213-1 :height any :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0   t nil nil 128 1 3 49))
      ((:char-spec japanese-jisx0213-1 :height any :weight bold :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0   t nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec latin-jisx0201 :height any)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0 nil nil nil 128 1 3 49))
      ((:char-spec latin-jisx0201 :height any :weight bold)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0 nil nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec latin-jisx0201 :height any :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0   t nil nil 128 1 3 49))
      ((:char-spec latin-jisx0201 :height any :weight bold :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0   t nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec latin-iso8859-1 :height any)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0 nil nil nil 128 1 3 49))
      ((:char-spec latin-iso8859-1 :height any :weight bold)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0 nil nil nil 128 1 3 49)
       ((spacing . -1)))
      ((:char-spec latin-iso8859-1 :height any :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 400 0   t nil nil 128 1 3 49))
      ((:char-spec latin-iso8859-1 :height any :weight bold :slant italic)
       (w32-logfont jiros-setting-font-family 0 jiros-setting-font-size 700 0   t nil nil 128 1 3 49)
       ((spacing . -1)))
      )))))



;; EOF
